# Generated by Django 5.1 on 2024-08-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_weatherdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='city',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
